# Generated by Django 5.1.5 on 2025-01-18 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('youtube_id', models.CharField(max_length=255)),
                ('twitter_id', models.CharField(blank=True, max_length=255, null=True)),
                ('youtube_pp', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('followers', models.IntegerField()),
                ('earnings', models.CharField(blank=True, max_length=255, null=True)),
                ('podcast_playlist', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('source_type', models.CharField(choices=[('youtube', 'YouTube'), ('twitter', 'Twitter')], max_length=255)),
                ('source_id', models.CharField(max_length=255)),
                ('claim', models.TextField()),
                ('validation', models.CharField(choices=[('verified', 'Verified'), ('questionable', 'Questionable'), ('debunked', 'Debunked')], max_length=255)),
                ('category', models.CharField(choices=[], max_length=255)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='influencers.influencer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
