# Generated by Django 5.1.5 on 2025-01-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("influencers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="score",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
