# Generated by Django 5.1.5 on 2025-01-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("influencers", "0003_claim_validation_sources_alter_claim_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="influencer",
            name="podcast_playlist",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
